# Generated by Django 4.2.15 on 2024-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='poollist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_list_name'),
        ),
    ]
