# Generated by Django 4.2.15 on 2024-09-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Сеть')),
            ],
            options={
                'db_table': 'blockchain',
            },
        ),
        migrations.CreateModel(
            name='DexNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='DEX')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.blockchains', verbose_name='Сеть')),
            ],
            options={
                'db_table': 'dex_name',
            },
        ),
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('usd_price', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Цена USD')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('transactions', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('makers', models.PositiveIntegerField(default=0, verbose_name='Количество makers')),
                ('volume', models.IntegerField(default=0, verbose_name='vol')),
                ('price_change_5m', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изменение цены 5 мин')),
                ('price_change_1h', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изменение цены 1 час')),
                ('price_change_6h', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изменение цены 6 часов')),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изменение цены 24 часа')),
                ('liquidity', models.IntegerField(default=0, verbose_name='Ликвидность')),
                ('mcap', models.IntegerField(default=0, verbose_name='mcap')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.blockchains', verbose_name='Сеть')),
                ('dex_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.dexnames', verbose_name='DEX')),
            ],
            options={
                'db_table': 'pool',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('symbol', models.CharField(max_length=15, verbose_name='Символ')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.blockchains', verbose_name='Сеть')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='TokenPools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.pools', verbose_name='ID пула')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pairs.tokens', verbose_name='ID токена')),
            ],
            options={
                'db_table': 'token_pool',
            },
        ),
        migrations.AddField(
            model_name='pools',
            name='token_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pairs_as_token_1', to='pairs.tokens', verbose_name='Токен 1'),
        ),
        migrations.AddField(
            model_name='pools',
            name='token_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pairs_as_token_2', to='pairs.tokens', verbose_name='Токен 2'),
        ),
    ]
